# Generated by Django 3.0.8 on 2020-07-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_card',
            field=models.IntegerField(default=0),
        ),
    ]
